In [1]:
import pennylane as qml

def my_quantum_function(x, y):
    qml.RZ(x, wires=0)
    qml.CNOT(wires=[0,1])
    qml.RY(y, wires=1)
    qml.AmplitudeDamping(0.1, wires=0)
    return qml.expval(qml.PauliZ(1))

In [2]:
op = qml.prod(qml.PauliX(0), qml.PauliZ(1))
op = qml.sum(qml.Hadamard(0), op)
op = qml.s_prod(1.2, op)
op

1.2 * (Hadamard(wires=[0]) + X(0) @ Z(1))

In [3]:
op = qml.RX(0.54, wires=0)
qml.matrix(op)

array([[0.9637709+0.j        , 0.       -0.26673144j],
       [0.       -0.26673144j, 0.9637709+0.j        ]])

In [6]:
import torch
x = torch.tensor(0.6, requires_grad=True)
matrix_fn = qml.matrix(qml.RX)
matrix_fn(x, wires=0)

tensor([[0.9553+0.0000j, 0.0000-0.2955j],
        [0.0000-0.2955j, 0.9553+0.0000j]], grad_fn=<StackBackward0>)

In [7]:
loss = torch.real(torch.trace(matrix_fn(x, wires=0)))
loss.backward()
x.grad

tensor(-0.2955)

In [10]:
from pennylane import numpy as np
def circuit(theta):
    qml.RX(theta, wires=1)
    qml.Z(wires=0)
qml.matrix(circuit, wire_order=[1,0])(np.pi / 4)

array([[ 0.92387953+0.j        ,  0.        +0.j        ,
         0.        -0.38268343j,  0.        +0.j        ],
       [ 0.        +0.j        , -0.92387953+0.j        ,
         0.        +0.j        ,  0.        +0.38268343j],
       [ 0.        -0.38268343j,  0.        +0.j        ,
         0.92387953+0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.38268343j,
         0.        +0.j        , -0.92387953+0.j        ]])